### ISSUE TITLE
What is plin?

### ISSUE THREAD

**Issue by avinassh** [antoviaque/plin#1]
Can you add more details to README? And also, it would be nice if you add a friendly OSS license

**Comment by antoviaque** [comment]
@avinassh I'm actually surprised anyone looked at this repo : ) - how did you hear about it?

It's just an old unfinished personal project, a review website for books made for a friend. It's not really meant to be reused. I've filled the description field and added a `LICENSE` file (AGPLv3).

**Comment by avinassh** [comment]
Hey I am your follower on Github, so in timeline it appeared you have open sourced this repo. So I checked but couldn't fine more info. I am teaching myself Django, so I thought learn more about this. Thanks!
